version: '3'

tasks:
  build:
    desc: Build cca binary
    cmds:
      - go build -o bin/cca{{if eq OS "windows"}}.exe{{end}} .
    sources:
      - "*.go"
      - internal/**/*.go
      - go.mod
    generates:
      - bin/cca{{if eq OS "windows"}}.exe{{end}}

  install:
    desc: Install cca to GOPATH/bin
    cmds:
      - go install .

  test:
    desc: Test cca with simple-api example
    dir: examples/simple-api
    cmds:
      - cca validate --quick
      - cca list
      - cca impact api-p99-latency

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f bin/cca{{if eq OS "windows"}}.exe{{end}}
      - go clean
